### PR TITLE
finished css-pseudo-classes exercise

### PR DESCRIPTION
**Pull request by qnpham**
Screen Shot 2022-08-24 at 9 55 16 AM

### CODE REVIEW

**Review by thebearingedge — CHANGES_REQUESTED** [review]
The user's cursor should change to a pointing hand when they hover over the button.

**Comment by qnpham** [comment]
https://user-images.githubusercontent.com/84756451/186478492-b54f6e7b-c90d-4da4-a694-9a77699655f6.mov

Sorry I forgot to record a video.

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Ok great, we just need the user's cursor to change to a pointing hand when they hover over the button

**Comment by qnpham** [comment]
https://user-images.githubusercontent.com/84756451/186481642-2d69f272-03f2-4977-a787-ce648d59a5f4.mov

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
